import { ShelfLifeItem } from '@/types';

export const SHELF_LIFE_DEFAULTS: ShelfLifeItem[] = [
  { keyword: '牛奶', category: 'dairy', days: 7 },
  { keyword: '酸奶', category: 'dairy', days: 21 },
  { keyword: '奶酪', category: 'dairy', days: 180 },
  { keyword: '黄油', category: 'dairy', days: 90 },
  { keyword: '奶粉', category: 'dairy', days: 540 },
  { keyword: '奶油', category: 'dairy', days: 7 },

  { keyword: '猪肉', category: 'meat', days: 3 },
  { keyword: '牛肉', category: 'meat', days: 3 },
  { keyword: '鸡肉', category: 'meat', days: 2 },
  { keyword: '鱼', category: 'meat', days: 2 },
  { keyword: '虾', category: 'meat', days: 2 },
  { keyword: '培根', category: 'meat', days: 7 },
  { keyword: '火腿', category: 'meat', days: 90 },
  { keyword: '香肠', category: 'meat', days: 30 },

  { keyword: '生菜', category: 'vegetable', days: 3 },
  { keyword: '白菜', category: 'vegetable', days: 7 },
  { keyword: '番茄', category: 'vegetable', days: 7 },
  { keyword: '西红柿', category: 'vegetable', days: 7 },
  { keyword: '黄瓜', category: 'vegetable', days: 5 },
  { keyword: '胡萝卜', category: 'vegetable', days: 14 },
  { keyword: '土豆', category: 'vegetable', days: 30 },
  { keyword: '马铃薯', category: 'vegetable', days: 30 },
  { keyword: '洋葱', category: 'vegetable', days: 30 },
  { keyword: '青椒', category: 'vegetable', days: 7 },
  { keyword: '西兰花', category: 'vegetable', days: 5 },
  { keyword: '菠菜', category: 'vegetable', days: 3 },
  { keyword: '芹菜', category: 'vegetable', days: 7 },
  { keyword: '韭菜', category: 'vegetable', days: 3 },
  { keyword: '茄子', category: 'vegetable', days: 7 },
  { keyword: '玉米', category: 'vegetable', days: 5 },

  { keyword: '苹果', category: 'fruit', days: 14 },
  { keyword: '香蕉', category: 'fruit', days: 5 },
  { keyword: '橙子', category: 'fruit', days: 14 },
  { keyword: '橘子', category: 'fruit', days: 14 },
  { keyword: '葡萄', category: 'fruit', days: 7 },
  { keyword: '草莓', category: 'fruit', days: 3 },
  { keyword: '西瓜', category: 'fruit', days: 7 },
  { keyword: '梨', category: 'fruit', days: 14 },
  { keyword: '芒果', category: 'fruit', days: 7 },
  { keyword: '菠萝', category: 'fruit', days: 7 },
  { keyword: '猕猴桃', category: 'fruit', days: 14 },
  { keyword: '桃子', category: 'fruit', days: 5 },
  { keyword: '樱桃', category: 'fruit', days: 7 },

  { keyword: '饼干', category: 'snack', days: 180 },
  { keyword: '薯片', category: 'snack', days: 90 },
  { keyword: '巧克力', category: 'snack', days: 365 },
  { keyword: '面包', category: 'snack', days: 7 },
  { keyword: '蛋糕', category: 'snack', days: 3 },
  { keyword: '方便面', category: 'snack', days: 180 },
  { keyword: '火腿肠', category: 'snack', days: 90 },
  { keyword: '辣条', category: 'snack', days: 120 },
  { keyword: '坚果', category: 'snack', days: 180 },
  { keyword: '瓜子', category: 'snack', days: 180 },
  { keyword: '糖果', category: 'snack', days: 365 },

  { keyword: '矿泉水', category: 'beverage', days: 365 },
  { keyword: '纯净水', category: 'beverage', days: 365 },
  { keyword: '可乐', category: 'beverage', days: 180 },
  { keyword: '雪碧', category: 'beverage', days: 180 },
  { keyword: '果汁', category: 'beverage', days: 7 },
  { keyword: '啤酒', category: 'beverage', days: 180 },
  { keyword: '白酒', category: 'beverage', days: 3650 },
  { keyword: '红酒', category: 'beverage', days: 1095 },
  { keyword: '奶茶', category: 'beverage', days: 1 },
  { keyword: '咖啡', category: 'beverage', days: 180 },
  { keyword: '豆浆', category: 'beverage', days: 2 },

  { keyword: '酱油', category: 'seasoning', days: 365 },
  { keyword: '醋', category: 'seasoning', days: 365 },
  { keyword: '盐', category: 'seasoning', days: 1095 },
  { keyword: '糖', category: 'seasoning', days: 730 },
  { keyword: '白糖', category: 'seasoning', days: 730 },
  { keyword: '料酒', category: 'seasoning', days: 365 },
  { keyword: '蚝油', category: 'seasoning', days: 180 },
  { keyword: '番茄酱', category: 'seasoning', days: 180 },
  { keyword: '豆瓣酱', category: 'seasoning', days: 180 },
  { keyword: '辣椒酱', category: 'seasoning', days: 180 },
  { keyword: '味精', category: 'seasoning', days: 730 },
  { keyword: '鸡精', category: 'seasoning', days: 365 },
  { keyword: '食用油', category: 'seasoning', days: 540 },
  { keyword: '花生油', category: 'seasoning', days: 540 },
  { keyword: '橄榄油', category: 'seasoning', days: 730 },

  { keyword: '罐头', category: 'other', days: 365 },
  { keyword: '大米', category: 'other', days: 180 },
  { keyword: '面粉', category: 'other', days: 180 },
  { keyword: '鸡蛋', category: 'other', days: 30 },
  { keyword: '挂面', category: 'other', days: 365 },
  { keyword: '速冻', category: 'other', days: 90 },
  { keyword: '水饺', category: 'other', days: 90 },
  { keyword: '馄饨', category: 'other', days: 90 },
  { keyword: '汤圆', category: 'other', days: 180 },
];

export const CATEGORY_LABELS: Record<string, string> = {
  dairy: '乳制品',
  meat: '肉类',
  vegetable: '蔬菜',
  fruit: '水果',
  snack: '零食',
  beverage: '饮料',
  seasoning: '调味品',
  other: '其他',
};

export const STORE_NAMES = [
  '沃尔玛超市',
  '家乐福',
  '永辉超市',
  '大润发',
  '盒马鲜生',
  '山姆会员店',
  '华润万家',
  '物美超市',
  '便利蜂',
  '7-Eleven',
  '全家便利店',
  '罗森',
];
